codecov:
  token: e5fb81bf-50f2-4d0a-afc4-b24e2f0efb8c
  require_ci_to_pass: yes
coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        threshold: 0%
        target: auto
    patch: off
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
